using RetailSphere.SharedKernel;

namespace RetailSphere.Domain.Notifications;

/// <summary>
/// An in-app (and optionally emailed) alert generated by the system — payment-due
/// reminders, overdue invoices, credit-limit breaches, etc. (see the AP/AR module's
/// Notifications &amp; Alerts requirements). Modeled as a plain Entity, not an
/// AggregateRoot, the same way AuditLog is: it's a simple write-once record with no
/// invariants to protect beyond "mark it read" / "mark its email sent" — created
/// explicitly by application-layer code (command handlers reacting to a state change,
/// or the daily Hangfire sweep job) rather than raised as a domain event, to keep
/// its content deliberately human-readable up front rather than reconstructed later.
/// </summary>
public sealed class Notification : Entity<long>
{
    /// <summary>
    /// Freeform code identifying what kind of alert this is (e.g. "SupplierPaymentDue",
    /// "SupplierInvoiceOverdue", "CustomerPaymentOverdue", "CustomerCreditLimitExceeded",
    /// "InvoiceUnpaidPastDue") — kept as a string rather than an enum so new alert types
    /// can be introduced without a migration; KnownTypes below are just the ones the
    /// system currently raises, not an enforced whitelist.
    /// </summary>
    public static readonly IReadOnlyList<string> KnownTypes =
    [
        "SupplierPaymentDue",
        "SupplierInvoiceOverdue",
        "CustomerPaymentOverdue",
        "CustomerCreditLimitExceeded",
        "InvoiceUnpaidPastDue",
    ];

    public static readonly IReadOnlyList<string> Severities = ["Info", "Warning", "Critical"];

    public string Type { get; private set; } = default!;

    public string Severity { get; private set; } = "Info";

    public string Message { get; private set; } = default!;

    /// <summary>e.g. "PurchaseInvoice", "SupplierPayment", "SalesOrder", "Customer", "Supplier" — lets the UI deep-link the notification to the record it's about.</summary>
    public string? RelatedEntityType { get; private set; }

    public long? RelatedEntityId { get; private set; }

    /// <summary>Null means it's a broadcast alert visible to everyone holding the relevant permission (e.g. all users with finance.payables.view) rather than one specific user's inbox item.</summary>
    public long? UserId { get; private set; }

    public bool IsRead { get; private set; }

    public DateTime? ReadAtUtc { get; private set; }

    /// <summary>True once the Hangfire notification sweep has successfully emailed this alert — prevents the same alert being emailed twice if the daily job re-scans overdue items it already reported.</summary>
    public bool EmailSent { get; private set; }

    public DateTime? EmailSentAtUtc { get; private set; }

    public DateTime CreatedAtUtc { get; private set; }

    private Notification()
    {
    }

    public static Notification Create(
        string type,
        string severity,
        string message,
        string? relatedEntityType,
        long? relatedEntityId,
        long? userId) => new()
    {
        Type = string.IsNullOrWhiteSpace(type) ? "General" : type.Trim(),
        Severity = Severities.Contains(severity) ? severity : "Info",
        Message = message,
        RelatedEntityType = relatedEntityType,
        RelatedEntityId = relatedEntityId,
        UserId = userId,
        CreatedAtUtc = DateTime.UtcNow,
    };

    public void MarkAsRead()
    {
        if (IsRead)
            return;

        IsRead = true;
        ReadAtUtc = DateTime.UtcNow;
    }

    public void MarkEmailSent()
    {
        EmailSent = true;
        EmailSentAtUtc = DateTime.UtcNow;
    }
}
