server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;

    location / {
        try_files $uri $uri/ /index.html =404;
    }

    types {
        application/wasm wasm;
    }

    gzip on;
    gzip_types application/wasm application/json text/css application/javascript;
}
